### ISSUE TITLE
DPL-831: Refactor sample sheets to better handle multiple versions, instruments, and libraries

### ISSUE THREAD

**Issue by StephenHulme** [sanger/traction-service#1058]
**Describe the Housekeeping**
Refactor sample sheets to better handle multiple versions, instruments, and libraries.

**Blocking issues**
- #1067
- #1085 

**Additional context**
As a follow-on to #993, the proposed solution (#1050) leaves room for improvement to maintain the quality of code going forward. An alternative implementation (#1057) provides additional ideas, but more work is required to form a simpler and more elegant solution.

This has resulted in #1067, part 1 - sample sheets to address the creation of the CSV.  
Part 2 of the solution addresses the instrument and version conflicts introduced by SMRT Link v12 for Sequel IIe.

**Comment by SujitDey2022** [comment]
Hi @StephenHulme, just wanted to check if this work is related to the Revio Phase level development or is an enhancement independent of the phases.
