### ISSUE TITLE
DPL-837 - As a long read user I need to validate the sequencing kit box barcode further to ensure that the correct wells are used (BP-Low ¦ Could've)

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1062]
**User story**
As a long read user I need to validate the sequencing kit box barcode further to ensure that the correct wells are used
e.g. if A1 is used on a run for a particual sequencing kit box barcode then B1, C1 and D1 can be used for a second run but not a first run.

**Who are the primary contacts for this story**
James / Craig / Steve

**Who is the nominated tester for UAT**
Craig

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The following combinations are not valid on a first run [B1], [B1,C1], [B1,C1,D1], [C1], [D1]
- [ ] The following combinations are not valid on a second run [B1], [B1,C1], [B1,C1,D1], [C1], [D1] if the preceding wells are used for the same sequencing kit box barcode. e.g. if A1 has been used with a particular sequencing kit box barcode then B1, C1 and D1 can be used with that same sequencing kit box barcode. If A1 and B1 have been used with a particular sequencing kit box barcode then C1 and D1 can be used on a second run and so on ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by SujitDey2022** [comment]
Discussed between Craig and Steve I. to be closed
