### ISSUE TITLE
DPL-846 - As long read (Craig) I would like to ensure that Revio single plate runs should be restricted to plate 1

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1072]
**User story**
As long read (Craig) I would like to ensure that Revio single plate runs should be restricted to plate 1

**Who are the primary contacts for this story**
Steve / Craig

**Who is the nominated tester for UAT**
Craig / Carlos

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] If a run is created in plate 2 only it should either be rejected or moved to plate 1

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by SujitDey2022** [comment]
Discussed between Craig and Steve I. to be closed
