### ISSUE TITLE
DPL-898 - As a Long Read user (Craig) I need to ensure that unbarcoded (untagged) samples have an entry in the Adapters / Barcodes field in the sample sheet as it is required

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1111]
**User story**
As a Long Read user (Craig) I need to ensure that unbarcoded (untagged) samples have an entry in the Adapters / Barcodes field in the sample sheet as it is required

**Who are the primary contacts for this story**
Craig / Steve

**Who is the nominated tester for UAT**
Craig

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When I create a v12 sample sheet for Revio there should be an adapters / barcode field for untagged samples
- [ ] When I create a v12 sample sheet for Sequel IIe it does not need an entry for the adapters / barcode field

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
UAT BUG (Missing feature?)
I have just stumbled across a possible missing feature for Revio Sequencing. It was definitely mentioned originally but may have just been missed from stories. Impact of missing feature will be low as most samples are barcoded but this will need to be addressed (include in Phase 4?) as untagged samples will not be able to be sequenced on Revio until implemented.
Unbarcoded(untagged) samples require an entry in the 'Adapters / Barcodes' field on the samplesheet even though they are untagged. i.e. untagged samples for the Revio samplesheet need to be treated as if they do have a tag/barcode...
However, for the Sequel II samplesheet this is not required (in SL12)...
I've attached the current samplesheet output and the amended file that should be generated for the Revio import.
[TRACTION-RUN-79 (1).csv](https://github.com/sanger/traction-service/files/12577105/TRACTION-RUN-79.1.csv)
[TRACTION-RUN-79edited.csv](https://github.com/sanger/traction-service/files/12577107/TRACTION-RUN-79edited.csv)

**Comment by BenTopping** [comment]
Closing as not required in newer SMRTLink veresions
