### ISSUE TITLE
DPL-949 - As a long read user (Craig) I would like the DNA control complex box barcode to be added to each well on a Sequel IIe SMRT Link 12 rather than each run so we can take advantage of adding the binding kit automatically

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1132]
**User story**
As a long read user (Craig) I would like the DNA control complex box barcode to be added to each well on a Sequel IIe SMRT Link 12 rather than each run so we can take advantage of adding the binding kit automatically

**Who are the primary contacts for this story**
Steve / Craig

**Who is the nominated tester for UAT**
Craig / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] DNA control complex box barcode should be available on each well in a run
- [ ] When the DNA control complex box barcode is added the binding kit should be added automatically
- [ ] If the DNA control complex box barcode is not added then an error should be raised
- [ ] If it is a Revio run then the DNA control complex box barcode is not required
- [ ] All existing runs should have the barcode moved to well level using a reusable script
- [ ] There will need to be a mapping betwee the DNA control complex box barcode, binding kit and binding kit box barcode

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
If the Revios are being phased out is there any need for this?

**Comment by stevieing** [comment]
Closed as will not be done if we are phasing out the Revios

**Comment by SujitDey2022** [comment]
Discussed with @stevieing and was mentioned to be closed as we have moved to newer version
