### ISSUE TITLE
DPL-965 Research - As a long-read user (James) I want the ability to create pools from samples or libraries to support revio multiplexing

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/traction-service#1137]
**User story**
As a long-read user (James W.) I want the system to pre-populate the sample Traction ID and related information or the pools created so that I do not have to manually re-enter all the corresponding information.

Multiplexing functionality exists in Traction, but as we increase the amount that we need to do it has identified some areas for improvement of the process - currently, we have to pool from a sample, which requires us to re-add all the information again per sample. What we would like to do is pool traction IDs (pools) as that is actually what we are doing in the lab. We are pooling libraries that have been made. This could also link in with the suggestions for volume tracking and reducing the remaining volume to reflect what has been taken into the pool

**Who are the primary contacts for this story**
James W.

**Who is the nominated tester for UAT**
James W.

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] An Entity Relationship Diagram (ERD) for pacbio multiplexing
- [x] A process diagram for how multiplexing will work
- [x] A set of stories to allow multiplexing from samples and libraries

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- [DPL-964 Research - Ability to track sample volumes and enable top-up management sanger/traction-ui#1136](https://github.com/sanger/traction-service/issues/1136)

**Additional context**
Eliminate duplication of data, speed up the multiplexing process, make volume tracking more accurate, reflect the process that actually occurs in the lab

**Comment by stevieing** [comment]
- When creating a new pool, the following information needs to be recorded for each sample:
- Template Prep Kit Box
- Barcode
- Volume
- Concentration
- Insert Size
- In long read, we typically make pools from existing libraries (which is stored as a single-plex pool in traction) e.g. Take half of TRAC-123 and half of TRAC-124 to make a new library of TRAC-125. IDs 123,124 and 125 would continue to exist as pools with volume
- As a long read lab user we would like to be able to make a pool using the existing information for each library that already exists in Traction.
- As a long read traction user we would like to select a number of libraries by their TRAC ID (min. 2 / max. 96) and have Traction populate all the required fields (e.g. concentration etc.)
- The only field that would require user input is the volume
- This would feed in to the previous story, whereby the volume of the original library would update to reflect the amount taken out in to the new library pool

**Comment by stevieing** [comment]
Process diagram

https://lucid.app/lucidchart/343de76c-d3e5-4a26-92c4-7bc10d919fb8/edit?viewport_loc=-844%2C-2242%2C3551%2C2094%2C0_0&invitationId=inv_13a8dd3b-ef1b-4f4e-b160-0dbf45a6031f

![Traction - Pacbio multiplexing - process map](https://github.com/sanger/traction-service/assets/519327/d48254ff-6973-4170-8269-7f0c2392eca4)

**Comment by BenTopping** [comment]
@stevieing Looks good, some nice work. Left a few comments on some of them. Some of the UI ones may need an additional acceptance criteria / research story for designing the pages as there are significant UI changes and will require talking to the lab.  Are DPL-992 and DPL-995 duplicates?

**Comment by stevieing** [comment]
> @stevieing Looks good, some nice work. Left a few comments on some of them. Some of the UI ones may need an additional acceptance criteria / research story for designing the pages as there are significant UI changes and will require talking to the lab. Are DPL-992 and DPL-995 duplicates?

The UI changes to the user will be minimal. The sequencing run will be exactly the same and pooling will be similar. Libraries will change a bit and will go back to the old way. DPL-995 is the store and DPL-992 is the view and component. We are going to move it over to Pinia so the 2 stores can co-exist.

**Comment by TWJW-SANGER** [comment]
In terms of releasing these stories I see roughly half the stories are modifying the underlying architecture / ERD etc - which won't be functional for the users.
The other half deliver functionality that users can test - to what extent can the functional stories be tested and released independently?
(I think you answered yes to this in our conversation before. But it might be worth calling out any specifics another developer should know on how that is achieved, if it's non-obvious.)

**Comment by stevieing** [comment]
> In terms of releasing these stories I see roughly half the stories are modifying the underlying architecture / ERD etc - which won't be functional for the users. The other half deliver functionality that users can test - to what extent can the functional stories be tested and released independently? (I think you answered yes to this in our conversation before. But it might be worth calling out any specifics another developer should know on how that is achieved, if it's non-obvious.)

I have created them in such a way that we should be able to release them independently (we may need feature flags).

The architecture changes are required before we do the functional stories but should have no impact on users.
