### ISSUE TITLE
DPL-986 - As developers we need to create an aliquot entity which can be used to create aliquots of samples and libraries for multiplexing and sequencing runs

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1150]
**User story**
As developers we need to create an aliquot entity which can be used to create aliquots of samples and libraries for multiplexing and sequencing runs

**Who are the primary contacts for this story**
James / Steve

**Who is the nominated tester for UAT**
PSD
**Acceptance criteria**
To be considered successful the solution must allow:
- [x] an aliquot to have a model with volume, concentration, insert size and template prep kit box barcode
- [x] an aliquot to have a tag (optional)
- [x] an aliquot to have a source which is a sample, library or pool
- [x] an aliquot to have a type - primary or derived
- [x] an aliquot to have a state e.g. created or used
- [x] an aliquot can have a uuid

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #1137
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by TWJW-SANGER** [comment]
Just comparing to the ERD. 
The acceptance criteria here specifies "an aliquot to have a source which is a _sample_, library or pool".
On the ERD _aliquot_ connects to _sample_ through a _request_ entity, or via a _library_ to _request_ to _sample_ relationship . 
 Is it worth clarifying what combinations are allowed, or a formal definition of _source_? Or have I got something backwards?
