### ISSUE TITLE
DPL-1041 - As a stakeholder (James W) I would traction to track PacBio SMRTLink Library Types.

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-service#1179]
**User story**
As a stakeholder (James W) I would traction to track PacBio SMRTLink Library Types.
Library type will be an attribute on a library / pool value. This is required for PacBio MAS-Seq.

**Who are the primary contacts for this story**
James W, Craig C

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ]  PacBio Revio libraries / pools should have a field for tracking SMRTLink Library Type.
   - Possible options: ‘Standard’, ‘Kinnex’, or ‘Adeno-associated Virus’
   - ‘Standard’ should be default.
- [ ] This value should dictate the ‘Library Type’ field in PacBio Revio v13 run sample sheets.

**Comment by BenTopping** [comment]
It would be worth confirming with long-read how they want this to work. Since this is a SMRTLink field it may be better off sitting as a well default in the run as opposed to a field on libraries/pools. This would probably reduce the size of this work.

**Comment by stevieing** [comment]
@BenTopping we will need to deploy this to training run the task and check if there is any data that needs fixing so probably best to do that on Monday when the data is most up to date?
