### ISSUE TITLE
DPL-1051 - As a long read user (James) I would like an estimate of the amount of work to track sample volumes and enable top-up management

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1186]
**Description**
This is a follow on from theresearch story:
- #1136

We now require a detailed list of the stories for prioritisation.

**Who the primary contacts are for this work**
James / Sujit / Steve

**Knowledge or Stake holders**
Long Read

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by BenTopping** [comment]
Do we want to include an investigation into the work to track volumes from a request level. I.e can we get sample volumes when we import them into traction from sequencescape.

**Comment by stevieing** [comment]
> Do we want to include an investigation into the work to track volumes from a request level. I.e can we get sample volumes when we import them into traction from sequencescape.

Good point. I suspect this will not need doing yet but I can mention it to James.

**Comment by stevieing** [comment]
Closed as done.
