### ISSUE TITLE
Revio Multiplexing - phase 3 - tasks

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1263]
**Describe the Housekeeping**
Tasks to ensure Revio Multiplexing will work

**Feature flags:**
- dpl_1112 - Enable once used_aliquots migration has been run for wells (all existing wells have used aliquots). This flag validates them and keeps them in sync with wells libraries and pools.
- multiplexing_phase_2_aliquot: Enable. Used to switch between pools views in the UI.
- dpl_989_ui  - Enable. Used to send primary aliquot data in the poolcreate page in the UI

**Data:**
- There are a series of data migration in the pacbio_aliquot_data rake task. There are specific ones for requests, libraries, pools and wells that are being run once serially in production to handle aliquot setup for existing data.
- If you reset your db and run the pacbio_data:create rake task it should create all the required aliquots. (edited) 

Linked stories:
- #1226
- #1153

**Comment by BenTopping** [comment]
Closing as in done.
