### ISSUE TITLE
Y24-238 - As developers we would like to add detailed documentation for SMRT Link versioning to inform other projects and users

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1395]
**Describe the Housekeeping**

As developers we would like to add detailed documentation for SMRT Link versioning to inform other projects and users:
- Create documentation in the traction repository (not confluence)
- Add any process diagrams as images
- Provide detailed documentation about how it works from a user perspective
- Provide detailed documentation about how it works technically
- Maybe create Architectural Decision Records (ADR)??

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

**Comment by dasunpubudumal** [comment]
The documentation for this is already set up: https://sanger.github.io/traction-service/smrt-link-versioning/. 

Please update [`/documentation/smrt-link-versioning/docs`](https://github.com/sanger/traction-service/tree/develop/documentation/smrt-link-versioning) directory with contents.
