### ISSUE TITLE
GPL-385 As a user I need to be able to create ONT samples

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#211]
**User story**
As a developer ONT samples need to be able to be created because samples can be imported from samples extraction or sequencescape

**Who the primary contacts are for this story**
Steve/Harry

**Acceptance criteria**
To be considered successful the solution must allow:

- Multiple samples can be created in one request
- Use GraphQL to create API
- Associated metadata should have already be pulled from SS/ SE so all all required data will be present in the request (dont need metadata)
- Samples need to create a tube with a barcode (outdated)
- Sucessfully create sample
- Sucessfuly GET sample/ samples

**Additional context**
Check what metadata is persisted and required / optional:
Fields required:
- study id
- species
- sample name
- DNA source
- Genome size
- Storage

Coupled to [Traction UI](https://github.com/sanger/traction-ui/issues/301)

**Comment by harrietc52** [comment]
Only need tags as metadata (only scenario 3/4)
Well position in plate
Other fields that are mandatory in the oseq_flowcell table

**Comment by stevieing** [comment]
Set up a v2 api
Add an endpoint for creating plate/wells/samples
Add a factory for creating plate/wells/samples

**Comment by stevieing** [comment]
Graph QL structure for sample mutation:
`
{
  plate {
    barcode
    wells {
      position
      sample {
        name
      }
    }
  }
}
`
