### ISSUE TITLE
GPL-386 As a user I need to be able to create ONT libraries

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#213]
**User story**
As a user I need to be able to create ONT libraries 

**Who the primary contacts are for this story**
Harry/Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- api accept plate barcode and tag set name
- creates tube with a barcode
- creates library and link to tube
- add tag to existing request, link request to library
- can get list of all libraries

**Comment by harrietc52** [comment]
- Library will be created with a name. Which is the DN number of the plate the samples have been pooled from, then dash (-), and then the number of the pool. For example. DN1234-1. See [scenarios](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Pooling+Scenarios) for number of pools per plate. It depends on the number of tags
- Tube will be created with a barcode

Automation:
This depends on one (possibly two) things
1. How many ONT tags we have, 24 or 96

                          | 24 ONT tags    | 96 ONT tags
not pre tagged  | 4 library tubes | 1 library tube
pre tagged        | 4 library tubes | 1 library tube

2. Where samples are pre tagged

**Comment by harrietc52** [comment]
Query libraries can return:
id
library tube barcode
plate barcode library has been pooled from
the wells the samples in the library has been pooled from eg 'A1-H8'
the tag_set used to pool the libraries

**Comment by Chris-Friend** [comment]
Tasks associated with this story:
* Creating the library model [348](https://github.com/sanger/traction-service/pull/348)
* Creating the library factory to build a library from plates [348](https://github.com/sanger/traction-service/pull/348)
* Adding relevant graphql endpoints: a mutation to create libraries, and a query to list all libraries [356](https://github.com/sanger/traction-service/pull/356)
* Also updating to use a join between library, request and tags [356](https://github.com/sanger/traction-service/pull/356)

Both above PRs will be merged into [GPL-386](https://github.com/sanger/traction-service/tree/GPL-386), and on completion this feature branch will be merged into develop

**Comment by Chris-Friend** [comment]
Further changes required following MVP update:
* remove request libraries join: a request should have a single library, and a library many requests
* check uniqueness of tags within library factory
