### ISSUE TITLE
GPL-387 As a user I need to be able to create an ONT run

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#215]
**User story**
As a user I need to be able to create an ONT run

**Who the primary contacts are for this story**
Harry/Steve

**Acceptance criteria**
To be considered successful the solution must allow:

Run required fields:
- Instrument name
- Experiment name
- State

A run has many flowcells. Flowcell required fields:
- Flowcell ID
- Flowcell position
- Kit selection
- Basecall model (High accuracy / Fast / No basecalling)

A flowcell has a library
Library required fields:
...

- Successfully created a pacbio run in the database
- can GET run/runs

**Additional context**
What events are created?
Any automation with ONT API?

## Breakdown of tasks

* Generate architecture of active record models.
* Create a factory for generating runs.
* Create GraphQL endpoints.
  * Retrieve libraries with filter to exclude those already associated with a flowcell.
  * Mutation to create runs.
* Update message specifications for ONT runs.
* Message over Rabbit when runs are created as part of the above mutation.

**Comment by harrietc52** [comment]
On run creation
- set experiment name
- create flowcells
- each flowcell have a uuid, position
- each flowcell is associated with a library

Unknowns
- store instrument name?
- store state?

**Comment by Chris-Friend** [comment]
[GPL-387](https://github.com/sanger/traction-service/tree/GPL-387) is the feature branch for this story. The storyy will be complete on merging this feature branch into develop

Tasks breakdown:
* _Add Ont::Run and Ont::Flowcell active models_. The run should store the instrument name (fixed and from config), the experiment name (id), state (see Saphyr run, e.g. 'pending'), and should have many flowcells. The flowcell a position, a uuid and must have a single library. The library relationship to a flowcell should be optional
* _Add run and flowcells factories_. This should take a list of library identifiers (names or ids) and generate a single run with many flowcells containing a single library
* _Add new GraphQL endpoints_. One to create an ont run. Update the existing libraries endpoint to allow returning only libraries that have not been assigned to a flowcell
* _Send flowcells message(s) to the MLWH_. This will require adding a new ont flowcells message config in the `pipelines.yml`, and should be called in the GraphQL controller after successful creation of the run. Generated message should be tested

**Comment by stevieing** [comment]
The message to the warehouse should contain the following fields. For each flowcell there will be a separate entry for each request in a library:

id_flowcell_lims: flowcell.id,
updated_at: timestamp,
sample_uuid: sample.external_id,
study_uuid: request.external_study_id,
experiment_name: run.experiment_name,
instrument_name: hardcoded e.g 'GXB12345',
instrument_slot: flowcell.position,
pipeline_id_lims: library_preparation_type (don't know where this is coming from at the moment),
