### ISSUE TITLE
GPL-403 - As a user I need a tag set for ONT

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#221]
**User story**
As an ONT user we need to have a tag set available to add to samples when creating libraries. This will be 96 tags

**Who the primary contacts are for this story**
Karen Oliver / Craig Corton

**Acceptance criteria**
To be considered successful the solution must allow:
1. When a library is created from a plate the tags should be available so these can be automatically added to the samples.

**Additional context**
What fields are required?

**Comment by stevieing** [comment]
would it be possible to use @JamesGlover new record loader.

**Comment by stevieing** [comment]
The tag set in question is ONT_EXP-PBC096.
We need to transfer this tag set into traction. Probably best to use a rake task or James record loader.
There are some questions that need to be answered by Keith first.

**Comment by stevieing** [comment]
Steps you will need to do to get this story working locally:
- checkout the sequencescape repo and set it up
- start a server
- go to the UAT tab
- generate a tag group with 96 tags and the correct tag group name

You can then use this tag group to test the rake task

I have spoken to Keith and they will use the tag oligo directly so need to align ids or names.

Probably best to name the tag group id sequentially e.g. if the tag group is called ONT_EXP-PBC096 the tag 1 should be called ONT_EXP-PBC096-01 and so on.

**Comment by Chris-Friend** [comment]
For clarity, this task requires that Traction queries sequencescape for the tag set
