### ISSUE TITLE
GPL-266	As long read team (Craig) I would like to add seven new fields to the sample sheet as these fields are required for smart link for a run

### ISSUE THREAD

**Issue by rl15** [sanger/traction-service#226]

**Comment by KatyTaylor** [comment]
Script for creating TagSet and updating Tags to be within it (make sure have run migrations first):

`set = TagSet.create!(name: 'Sequel_16_barcodes_v3', uuid: '4d87a8ab-4d16-f0b0-77e5-0f467dba442e')`

`Tag.update_all(tag_set_id: set.id)`
