### ISSUE TITLE
Improve date time format

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/traction-service#260]
DateTime format in the initializer is currently set to 12 hour clock, but it doesn't show 'am' or 'pm' so is ambiguous. Change it to 24 hour clock.

It is set here:
https://github.com/sanger/traction-service/blob/develop/config/initializers/date_and_time_formats.rb

Can be changed using these rules:
https://apidock.com/ruby/DateTime/strftime

**Comment by BenTopping** [comment]
changed in PR #262
