### ISSUE TITLE
GPL-263a As Craig I would like the ability to add a pre-extension time to the well for a run as this is required for the sample sheet and I currently have to enter it manually

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#268]
Acceptance criteria:
- when I enter information for a well there should be a yes/no field for pre-extension time.
- if yes and pre-extension time of 2hrs with the option to change manually
- if no add a pre-extension time of 0
- add pre-extension time to sample sheet

**Comment by stevieing** [comment]
RT ticket #679888
Hi Steve/ Harry,
I’ve heard back from PacBio regarding the pre-extension field I was asking to be added to the sample sheet during the run set-up.
In the SMRT Link user guide it is listed on page 15. The field that is required in the csv file generated is:
Header Name: Automation Parameters
Example if not selecting an extension time (Blank):
Example if we want an extension time of 2 hours: ExtensionTime=double:2|ExtendFirst=boolean:True

 

The manual mentions time in minutes but this is a mistake it should be hours.

 

Kind regards,

Craig

**Comment by harrietc52** [comment]
1)      Need to be able to include pre-extension times for wells if required (ToL samples all currently need this)
a.       New column required in samplesheet ‘Automation Parameters’, if CLR can be left blank, if CCS should be along the lines of:
ExtensionTime=double:2|ExtendFirst=boolean:True
 
2=extension time required in hours

**Comment by harrietc52** [comment]
Sequencing mode:

CLR - CSV can be 
CCS - field should appear where they can enter pre extension time

pre extension file - number field - not required

**Comment by harrietc52** [comment]
Coupled with https://github.com/sanger/traction-ui/issues/497

**Comment by KatyTaylor** [comment]
Questions and reply from Craig:

Katy:

> It seems like you will be mostly using a ‘pre-extension time’ with the CCS sequencing mode. Will that always be the case, or might you want to use it in the CLR mode at some point? I’m wondering whether or not to restrict it, so that it’s impossible to create wells with pre-extension times on CLR runs.
Is there conceptually a difference between ‘pre-extension time’ being not set, and it being ‘0’? I guess if you enter 0 that means you’re not using the feature and the ‘Automation Parameters’ column should be left blank on the spreadsheet?

Craig:

> 1.  Unfortunately, there will be times when we would want to use a pre-extension for CLR and as we can no longer upload sample sheets and edit I think we now need to build in a bit more flexibility in Traction.
> 2.  No, like you say, if we enter 0, it’s not being used so the cell can be blank for the well in question. It would be nice if:
a. CLR sequencing mode is selected, the default value is 0
b. CCS sequencing mode selected, the default value is 2

**Comment by KatyTaylor** [comment]
Need to run this with full_deploy=true

(Had an issue on UAT that it didn't pick up the new code, from Ben's fix, until we re-ran the deployment with full_deploy=true)
