### ISSUE TITLE
GPL-388 As a user I need to be able to edit ONT runs 

### ISSUE THREAD

**Issue by harrietc52** [sanger/traction-service#317]
**User story**
As a user I need to be able to edit ONT runs 

**Who the primary contacts are for this story**
Steve/ Harry

**Acceptance criteria**
To be considered successful the solution must allow:
1. Changing the state of an existing run.
2. Replacing the flowcells (associated libraries) of an existing run.

**Additional context**
This can be implemented as a single GraphQL mutation endpoint for updating a run.  The run will be identified by its `id` and can alter the `state` or the entire list of `flowcells`.  The existing flowcells will be destroyed and replaced with newly generated ones.

We also need to consider which event messages are sent over RabbitMQ.  Libraries/Samples that are moved to another flowcell will be easy for the warehouse to identify as being updated if we only send messages for their new location.  But Libraries/Samples that are removed from the run will not be so easy to identify if messages aren't created for them.

**Comment by stevieing** [comment]
Record the run time

**Comment by harrietc52** [comment]
Dont need to alter the state of a run, only flowcell library posiitons
