### ISSUE TITLE
GPL-421 As NPG I would like to support for adding multiple tags to a sample

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#331]
**User story**
As ONT protocols now allow multiple tags (e.g. 24 native barcodes plus 96 PCR barcodes to give 2,304 plex) so we should consider having space for additional tag information, as for Illumina

**Who the primary contacts are for this story**
Keith James

**Acceptance criteria**
To be considered successful the solution must allow:
1. I should be able to add multiple tags to a sample (request)

**Additional context**

**Comment by stevieing** [comment]
Interesting. tag_index and tag_identifier columns in iseq_flowcell seem to have the same content as each other, but slightly different definition comments.

Meanwhile, the tag_identifier column comment in the pac_bio_run table is "Tag index within tag set, NULL if untagged", which is more like tag_index.

There isn't an established term for ONT, so now is the time to change it if we want. I think tag_index is a better name.

**Comment by stevieing** [comment]
Dual indexing on samples:

It's a second barcode allocated to a single sample in the pool.

In Illumina these help prevent mis-assignment during deplexing .

https://support.illumina.com/bulletins/2018/08/understanding-unique-dual-indexes--udi--and-associated-library-p.html

In ONT it allows for deeper multiplexing because they have a 24-barcode protocol and a 96-barcode protocol that can be used together to give 24 * 96 samples in a pool.

So it has a different reason for being there in ONT compared to Illumina, but to me it seems helpful to retain the column name.

**Comment by Chris-Friend** [comment]
The requirements for this task are met by the changes made for [GPL-426](https://github.com/sanger/traction-service/issues/336) in which we allow adding multiple tags to a single Ont::Request/Sample
