### ISSUE TITLE
GPL-426 As an ONT user I need to be able to create samples that are prebarcoded (pretagged)

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#336]
**User story**
As an ONT user I need to be able to create samples that are prebarcoded (pretagged). Samples may be using 96 PCR barcodes designed in house. 

**Who the primary contacts are for this story**
Karen Oliver

**Acceptance criteria**
To be considered successful the solution must allow:
1. If a plate exists with samples that are using in-house PCR barcodes then these barcodes will need to be attached to samples when they are created in traction

**Additional context**

**Comment by Chris-Friend** [comment]
Feature branch: https://github.com/sanger/traction-service/tree/GPL-426
Development branches to me merged into this feature branch:
* https://github.com/sanger/traction-service/tree/GPL-426-move-tubes
* https://github.com/sanger/traction-service/tree/GPL-426-tag-taggable-join
* https://github.com/sanger/traction-service/tree/GPL-426-many-materials
* https://github.com/sanger/traction-service/tree/GPL-426-tag-requests
