### ISSUE TITLE
GPL-445 Investigate performance issues around creating plates

### ISSUE THREAD

**Issue by sdjm-tessella** [sanger/traction-service#355]
**Description**
Having created rake tasks to generate plates with 96 tagged samples in each of 96 wells, it has become clear that performance in creating plates has become an issue.  We need to investigate the underlying cause of this since the requests take too long right now and should, ideally, be under 30 seconds.

**Users**
Stephen Inglis

**Knowledge or Stake holders**
Stuart McHattie and Chris Friend developed the factories related to plate/well/sample creation.

**Additional context or information**
A partial investigation has already been done on this issue.  Some optimisations were put in place.  The results of which are as below:

Before any optimisation: 300+ seconds to create the pooling scenario 3 plate.
Optimising tag fetching for samples in wells: 293 seconds.
Removing duplicate validation at the start of factory save methods: 229 seconds.
Running the database as MySQL: 179 seconds.

These are all based on performance of a development MacBook Pro.  UAT ran these queries quicker, but still quite slowly.

The queries being executed in MySQL during the plate creation [is attached](https://github.com/sanger/traction-service/files/4586276/development_mysql.log.zip).  This file may be small as a .zip but inflates to 29MB of SQL statements.  At the bottom of these logs, it shows that ActiveRecord is taking up around 32 seconds, so the rest must be processing we are doing.  There are also 141.5 million allocations made.  The number of objects going into ActiveRecord should be 1 plate, 96 wells, 9,216 samples, 9,216 join objects, and 9,216 tag joins.  So the numbers are significantly lower than the allocations being made.

A good approach to this investigation could be to remove branches of the factory tree.  i.e. what happens if we don't apply tags to the samples?  What about if we look up the tags but don't create the samples?  If we can narrow the time hog to the object that's causing it, we can likely optimise the process.

**Comment by sdjm-tessella** [comment]
I started investigating the plate creation issues further as I added tests to our factories.  It turns out the RequestFactory is validating three entities Ont::Request, Sample and Request even if we ask the `save` method to not perform validation.  This is because they each have relationships to each other with `autosave` implicitly set to `true`.  There is an issue on the rails repository (https://github.com/rails/rails/issues/21058) which seems to indicate others have had this problem.  Someone created a PR to fix it, but it waited so long to merge that it got auto-closed without merging.  I think this is a bug in rails and we might not be able to fix that.  I only saw a reduction of approximately 30 seconds out of the remaining 229 it takes to generate a plate for pooling scenario 3 so this is not our biggest chunk of the remaining time we need to optimise for.  It is frustrating though.  More investigation will be needed to resolve this and other delays in the plate creation.

**Comment by stevieing** [comment]
It is also clear that there are performance problems creating a run from 4 96 well plates. There is a noticeable slow down when clicking the create plate button.
It looks like most of this is down to generating the messages and loading the tags. We are creating 384 messages.
Need to look at optimising queries that load libraries or running it asynchronously.
We could also look at the front end and priciding a spinner.

**Comment by Chris-Friend** [comment]
A [new issue](https://github.com/sanger/traction-service/issues/407) has been created for the performance improvement changes made in [GPL-445](https://github.com/sanger/traction-service/pull/404)

**Comment by Chris-Friend** [comment]
In an attempt to dramatically reduce the number of queries made to the database, and therefore improve performance, we investigated using Rails's [insert_all](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-insert_all) method. This generates a single INSERT query for many same-type entities. I.e. in the best case scenario we would be doing 5 bulk inserts as oppose to 100,000+.

However, `insert_all` has limitations, specifically to do with inserting objects which are uniquely defined by their associations only. This is the case we are facing: you have to put all the associations in yourself by knowing IDs for one object and putting that ID in the appropriate field for another object. You insert all the requests at once, say, without knowing their ids up front. Then you can't be sure which request is which or even if you can rely on the last x requests in the database being the ones you just inserted. So you don't know which ids to associate with each containing well.

The solution is to ensure each entity you insert into the database can be fetched by a unique combination of attributes excluding `id`, or by a relationship to one such entity. E.g. on inserting a plate you can fetch it back using its barcode, and on inserting wells you can fetch them back by their association to a plate.

As an Ont request cannot be uniquely defined by its attributes (or associations at the point of insert), we need to update it to be so. One idea would be to make it `uuidable`. We could store a reference to these before inserting, then fetch from the database using these uuids after inserting. We'd then have access to a request's id, and could use this and some cached hierarchy to update the database's associations (add our containermaterial and tagtaggable join rows)

**Comment by Chris-Friend** [comment]
Optimisation has been achieved by implementing as suggested above:
* Add a `uuid` to an Ont::Request on creation so it can be fetched back from the database, and its `id` used to add relevant ContainerMaterials and TagTaggables
* Bulk insert all entities into the database using the `insert_all` method
* Only fetch required tags once per plate insertion, rather than once per request/sample
