### ISSUE TITLE
GPL-451 Saphyr bug MLWH message

### ISSUE THREAD

**Issue by harrietc52** [sanger/traction-service#359]
**Describe the bug**

Saphyr flowcell association with library is broken. Therefor mlwh mesages, where the pipeline config specifies attributes of a library fail to be added. Resulting in the message being rejected from MLWH

**Comment by sdjm-tessella** [comment]
I had a look at this and couldn't find any issues with the warehouse populating when I use the data seeded from our rake tasks.

**Comment by stevieing** [comment]
It looks like this could be a ui problem when a Saphyr run is created. Less serious than broken data.
