### ISSUE TITLE
GPL-nnn As a developer I would like to add user authentication

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-service#535]
**User story**
The aim of this story is to increase the level of security within traction and only allows certain users to edit and create data in traction.

Coupled with UI issue: https://github.com/sanger/traction-ui/issues/571

**Who are the primary contacts for this story**
N/A

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Get a list of all users that need to be able to edit and create data in traction
- [ ] Add a user class which contains: swipe card, status
- [ ] Store all traction users in a new table
- [ ] encrypt each users swipe card when it is stored (can be hashed)

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Closed as too old. Authentication may still be required.
