### ISSUE TITLE
GPL-nnn As a long read user I would like to select a certain amount of volume from a library to move forward to library prep for pre lib QC and pooling

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-service#542]
**User story**
As a long read user I would like to select a certain amount of volume from a library to move forward to library prep for pre lib QC and pooling. Some volume may be left over In some cases libraries may be processed a second time.

Coupled with: https://github.com/sanger/traction-ui/issues/578
**Who are the primary contacts for this story**
N/A

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] allow a library to be split my an amount of volume

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Superceded by volume tracking work.
