### ISSUE TITLE
GPL-991 - As a long read user (Craig) I need a new tag group for bacterial multiplexing (C=S, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#556]
**User story**
As a long read user (Craig) I need a new tag group for bacterial multiplexing

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The microbial multiplexing tag set should be available in the service
- [ ] When I create a new pool the barcterial multiplexing tag set should be available

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Email from Craig (27/09). As I see it there are two options:
 
1)      We can import this new group of 48 tags (attached) into SMRTLink for use, it will be given a new data set UUID and you can call the tag group “48_Microbial_Barcoded_OHA_v1”. This tag group can then be used in traction for pooling microbial samples and the new UUID is referenced during run set up.
2)      Traction uses the tag IDs in the attached file (can still call the tag group “48_Microbial_Barcoded_OHA_v1”) but when it comes to the UUID for the tag group that is used during the run set up the UUID for the 96 tag file is used for the samplesheet.
 
I prefer option 2 as that is how we are currently working but if you prefer option 1 then that is also fine – I just need to import a new file to SMRTLINK for use.

**Comment by stevieing** [comment]
Tag set:

>bc1007T
TCTGTATCTCTATGTGT
>bc1023T
CAGAGAGATATCTCTGT
>bc1024T
CATGTAGAGCAGAGAGT
>bc1026T
CACAGAGACACGCACAT
>bc1027T
CTCACACTCTCTCACAT
>bc1028T
CTCTGCTCTGACTCTCT
>bc1029T
TATATATGTCTATAGAT
>bc1031T
GATGTCTGAGTGTGTGT
>bc1033T
TCTCGTCGCAGTCTCTT
>bc1034T
ATGTGTATATAGATATT
>bc1036T
GAGACACGTCGCACACT
>bc1037T
ACACATATCGCACTACT
>bc1040T
TGTCATATGAGAGTGTT
>bc1043T
TATAGAGCTCTACATAT
>bc1044T
GCTGAGACGACGCGCGT
>bc1046T
GATATATCGAGTATATT
>bc1047T
TGTCATGTGTACACACT
>bc1050T
GATATACGCGAGAGAGT
>bc1052T
GTGTGAGATATATATCT
>bc1053T
CTCACGTACGTCACACT
>bc1054T
GCGCACGCACTACAGAT
>bc1055T
CACACGAGATCTCATCT
>bc1057T
GACGAGCGTCTGAGAGT
>bc1058T
TGTGTCTCTGAGAGTAT
>bc1059T
CACACGCACTGAGATAT
>bc1060T
GATGAGTATAGACACAT
>bc1061T
GCTGTGTGTGCTCGTCT
>bc1062T
TCTCAGATAGTCTATAT
>bc1064T
TATATACAGAGTCGAGT
>bc1065T
GCGCTCTCTCACATACT
>bc1066T
TATATGCTCTGTGTGAT
>bc1067T
CTCTATATATCTCGTCT
>bc1068T
AGAGAGCTCTCTCATCT
>bc1070T
TGCTCTCGTGTACTGTT
>bc1074T
TGTACGCTCTCTATATT
>bc1076T
GTGCACTCGCGCTCTCT
>bc1077T
TATCTCTCGAGTCGCGT
>bc1078T
CTCACACATACACGTCT
>bc1079T
ATAGTACACTCTGTGTT
>bc1081T
GATATATATGTGTGTAT
>bc1082T
GTGACACACAGAGCACT
>bc1083T
ATATGACATACACGCAT
>bc1084T
CGTCTCTCGTCTGTGCT
>bc1087T
CTATCTAGCACTCACAT
>bc1091T
GTATATATATACGTCTT
>bc1092T
TCTCACGAGAGCGCACT
>bc1094T
ATAGCGACATCTCTCTT
>bc1095T
GCACGATGTCAGCGCGT

**Comment by JamesGlover** [comment]
Email sent:

> Unfortunately I think option 1 is the safest, as re-using UUIDs for multiple tag sets is likely to cause confusion or problems further down the line.
>  
> Am I correct in understanding that SMRTLink will generate a UUID when you upload the new file, and we subsequently record this in traction? If so, would it be possible to get the new set registered and let us know what the UUID should be?
>  
> If I’ve misunderstood, and you can provide SMRTLink with a UUID then let me know and I can easily go ahead and generate one.

**Comment by JamesGlover** [comment]
Response:

> OK, understood that option 1 is safer.
>  
> I have imported the tag group “Sequel_48_Microbial_Barcoded_OHA_v1”, the UUID is:
> c808dbb2-a26b-cfae-0a16-c3e7c3b8d7fe
