### ISSUE TITLE
DPL-124 - Add the concept of library type to a request (C=M, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#639]
**User story**
NPG need to be able to identify IsoSeq runs. To that end we need to add the concept of library type

**Who are the primary contacts for this story**
Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] When a sample is imported it can accept library type (not required)
- [x] When a run is exported to the MLWH it will include the library type if it exists

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
Huh, it appears that we already have a library_type column in the pacbio_request table

**Comment by JamesGlover** [comment]
Back end wise this seems to be pretty much in place, with just the message to the warehouse missing the key.

**Comment by JamesGlover** [comment]
So this story as it stands was trivial, and was just a matter of adding a bit of configuration however we will need:

1) Add the column pipeline_id_lims to the warehouse (Matches naming of equivalent field in other tables)
2) Add ability to set library type to reception pages

Also if we wanted to allow pass through from SS we will need:

1) Add library_type to the V2 aliquot resource.
2) Create a pacbio library plate manifest type with this column included
3) Update the library setting above to allow using the type coming in from Sequencescape.

**Comment by JamesGlover** [comment]
See: https://github.com/sanger/unified_warehouse/pull/314 for WH changes
