### ISSUE TITLE
DPL-215 - [BUG] Handle IsoSeq samples in SMRTLINK

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-service#675]
**Describe the bug**
As a user (Craig) I would like to be able to generate sample sheets with IsoSeq samples in that can be uploaded to SMRTLINK without errors. A new version of SMRTLink (v10.2) prevents the IsoSeq sample work around we have. Email chain in comment on email with more details.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**

- [ ] “Sample is barcoded”: FALSE
- [ ] “Barcode Set”: Blank
- [ ] Sample level: Barcode name blank
- [ ] Sample level: Bio Sample name blank
- [ ] Well level: BioSample name present (concatenated?)

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by BenTopping** [comment]
Hi Craig,
From my understanding the run design in SMRTLINK v10.2 can now detect if there are barcoded samples in a well even if we set the ‘Sample is Barcoded’ field to false. This is an issue as it prevents the current IsoSeq tag work around we have. Attached is a screenshot of the error message and a sample sheet I generated from RUN-86 in UAT which contains some IsoSeq tagged samples.
 
From my understanding the optimal fix would be to change the ‘Sample is Barcoded’ field to its original functionality which is to determine whether the samples have tags, even for IsoSeq samples. We would then need to update the IsoSeq tagset in traction to the correct tag format that smrtlink would recognise. 
 
An email from back in August:
“ IsoSeq samples will introduce further problems. SMRTLink will be expecting primers to be named the following way:
>bc1001_5p
>bc1001_3p
So the barcode name should be:
bc1001_5p--bc1001_3p with the flag of ‘Same Barcodes on Both Ends of Sequence’ set for FALSE (i.e a different tag sequence at either end) in SMRTLINK "
 
 
Thanks,
Ben


N.B Will add more information once Craig has heard back from PacBio about handling IsoSeq tags in SMRTLink

**Comment by stevieing** [comment]
Email from Craig (05/01)

To clarify for isoSeq libraries we need the run design set as follows:
“Sample is barcoded”: FALSE
“Barcode Set”: Blank (although don’t know if it matters if this is filled in without other information present)
and then no individual row information supplied regarding the “barcode name” and “Bio Sample Name”
 
I believe “Bio Sample Name” will still require an entry to be present on the main row, this could just be the Sample names concatenated. It does not matter to me what is in this field – more what is required for anything behind the scenes. SMRTLink dictaties that this is a required field if ‘sample is unbarcoded’

**Comment by JamesGlover** [comment]
Plan is to add new column to tag_sets `sample_sheet_behaviour` which will be an enum with two values at the moment:

0 = default
1 = hidden

These will map to classes which can handle the different behaviour.

**Comment by JamesGlover** [comment]
It *might* be that this behaviour would be better located on library type, but currently this is just a property on request. I can certainly see us moving towards:

1) A library_types table, with library types belonging to pipelines
2) Tag groups could in turn belong to library_types instead of pipelines
3) Library types could then be extended with custom behaviour

This would also potentially let us unify our receptions, with library type then indicating which pipeline something ended up in.
