### ISSUE TITLE
DPL-276 - ONT - Archive existing data [C=S, V=3]

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#708]
**User story**
The existing data is related to the experimental Covid work. It is already in the warehouse but it would be worth taking an SQL dump and archiving it

**Who are the primary contacts for this story**
James / Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Dump of ONT related tables to a safe space
- [ ] Empty current tables in UAT 
- [ ] Empty current tables in production (should be done as a buddy task)

**Additional context**

**Comment by stevieing** [comment]
Dear Stephen,
--


Dear Stephen,
 
Regarding your Service Request 334052
 
I have dumped the traction_service_production schema and sent it to the NetBackup system using the Archive-2-YR retention schedule.
 
If it needs to be recovered, these are the details you will need to provide to the DBA team to identify the backup job:
 
Client: mcs16
Date: 19 May 2022
Directory: /mysql_bkup_01/dumpfiles/psdp_3305/
 
Best regards
 
David

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
