### ISSUE TITLE
DPL-277 - ONT - Create samples and requests [C=M, V=4]

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#709]
**User story**
When a tube or plate is scanned into the reception from Sequencescape or Samples Extraction with a library type we need to create samples and associated requests

**Who are the primary contacts for this story**
Steve / James

**Acceptance criteria**
To be considered successful the solution must allow:

- [ ] creation of samples
- [ ] creation of requests with the following attributes ...
- [ ] endpoint for creating samples and requests from labware - plates or tubes
- [ ] creation of reception model
- [ ] creation of reception resource
- [ ] creation of reception endpoint
- [ ] implement flipper for feature flags

References
This story is related to sanger/traction-ui#706

**Comment by JamesGlover** [comment]
Sorting out attributes on requests:

Ont Heron:
- [ ] Name

Traction original (work-orders):
- [ ] Library Prep type
- [ ] Data Type
- [ ] Number of flowcells

On Pacbio:
- [ ] Library type
- [ ] estimate of gb required
- [ ] Number of smart cells
- [ ] Costcode
- [ ] External study id
- [ ] source_barcode

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
