### ISSUE TITLE
DPL-332 [BUG] Samples Extraction barcodes cannot be uploaded into Traction [C=S, V=4]

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#740]
**Describe the bug**
Samples Extraction barcodes cannot be uploaded into the Saphyr reception

**RT Ticket Number**
SE267589L
SE267590E
 
Traction Error : sample must exist, requestable must exist   
 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**
This may also affect importing extractions for PacBio.

**Comment by stevieing** [comment]
This issue is caused by code drift. The shared controller does not have the required parameters. We could modify this but it makes more sense to refactor the Saphyr code so the controllers, models and factories for this are separate so as not to cause any more problems in the future. To this end the tasks are:

- [ ] refactor the Sahyr Request model tests so they are not shared
- [ ] refactor the Saphyr Request model so it is not shared
- [ ] refactor the Saphyr Request Factory tests so they are not shared
- [ ] refactor the Saphyr Request Factory so it is not shared
- [ ] refactor the Saphy Requests spec so it is not shared
- [ ] refactor the Saphyr Requests Controller so it is not shared
- [ ] refactor the Saphyr Request Resource so it is not shared

**Comment by stevieing** [comment]
So looks like the error is caused by an incorrect payload to traction service. To fix this I will:

- [ ] Modify the store tests so that the payload is tested (tests/unit/store/traction/saphyr/tubes/actions.spec.js)
- [ ] Modify the store so that the correct payload is sent (store/traction/saphyr/tubes/actions.js)

**Comment by harrietc52** [comment]
These various errors are now handled when importing Sample Extraction tubes into Saphyr Reception.
First: when Traction could not connect to Samples Extraction
Second: when two SE barcodes were given, but only one was know in SE, so only one created. The other barcode dismissed.
Third: when there was one unknown SE barcode provided

![Screenshot 2022-04-13 at 12 29 55](https://user-images.githubusercontent.com/11446617/163170738-a76df74c-2a79-404e-9b0a-3e648ea56d2d.png)

**Comment by harrietc52** [comment]
Deploying to UAT `ansible-playbook -vD deploy_traction_ui.yml -i environments/uat -e "github_branch=v4.5.0-2232121066-develop"`
