### ISSUE TITLE
DPL-478 - As a Developer I need an API endpoint to allow users to upload a QC results spreadsheet

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#815]
**User story**
As a Developer I need an API endpoint to allow users to upload a qc results spreadsheet

**Who are the primary contacts for this story**
Steve

**Who is the nominated tester for UAT**
This can be done within PSD. UAT would need to ensure that it still works with the front end

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Addition of status column to the qc results table. Decision on the QC outcome (free text field)
- [x] Addition of decision made by column to the qc results table to allow reporting of who made the status decision e.g Long Read or ToL so that decisions can be made independently by various stakeholders
- [x] An agreed csv format
- [x] The creation of a create only JSON API compliant endpoint which will accept a csv
- [x] A model which will be a record of the csvs uploaded. Do we need to save the raw data?
- [x] An associated factory which will handle the csv data and transform it into qc results
- [x] Validation to ensure that the qc results are correct
- [x] JSON API resource which will provide feedback on success or provide errors
- [ ] An agreed message format to send the qc results to the warehouse
- [ ] A handler to send the message to the warehouse
- [ ] modification of qc type column so that it can recognise different label (OPTIONAL - to decide)

**Dependencies**

- sanger/unified_warehouse#397
- sanger/traction-ui#885

**References**
This story has a non-blocking relationship with:
- sanger/traction-ui#855

**Additional context**

- The above story is the originator but has been split out
- We will need the agreed csv format before progressing
- It is possible to split this story into sub stories e.g. creating the message structure

**Comment by stevieing** [comment]
As per meeting with Hermione and Lucy on 22/09:
- They would like the status to be recorded and for the team who have made the decision to be recorded so decisions can be made independently.

**Comment by stevieing** [comment]
Lucid chart diagram to show how the qc results are recorded and stored.

https://lucid.app/lucidchart/62e931d9-5afc-40db-a885-533196afb88a/edit?viewport_loc=285%2C-55%2C2549%2C1546%2C0_0&invitationId=inv_623f65cd-4e79-41d8-bd80-e367445d3ab8#

**Comment by stevieing** [comment]
Comparison of system column names and extraction headings

https://docs.google.com/spreadsheets/d/103tq5LMt92PepzBF-J4TepuuILFXsPr3lOYpysz9yJI/edit?usp=sharing

**Comment by harrietc52** [comment]
Questions
- [ ] The CSV uploaded to the UI, will that include the top line of groupings?
- [ ] Are all the Green columns wanting to be stored in Traction?
- [ ] For each mapping, could we confirm if they match to existing field in rake task

**Comment by harrietc52** [comment]
- Always have LR decision, sometimes have TOL
- Done need to store `Femto dilution`
- Herminore to add system field name for `Femto Frag Size`
- Herminore to look into headers can be unique
