### ISSUE TITLE
DPL-934 - As developers we need to remove the pacbio_well_libraries table from traction as it is no longer in use

### ISSUE THREAD

**Issue by harrietc52** [sanger/traction-service#955]
**Describe the Housekeeping**

As developers we need to remove the pacbio_well_libraries table from traction as it is no longer in use

**Additional context**
It's use was deprecated when we moved to pools.

**Comment by BenTopping** [comment]
This was reused temporarily due to the aliquot work but it has been removed in https://github.com/sanger/traction-service/pull/1274.
