### ISSUE TITLE
DPL-708 - As developers we need to add validation for the SMRT Link 12 Revio version options to ensure that the columns on the sample sheet contain the correct data

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#964]
**User story**
As developers we need to add validation for the SMRT Link 12 Revio version options to ensure that the columns on the sample sheet contain the correct data

**Who are the primary contacts for this story**
Steve / Craig / James

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:

Run-level: (scope moved to  #966 )
- [x] Library type is automatically generated and will always be standard
- [x] Reagent plate is a number and is limited to 1 or 2
- [x] Plate 1 should be a valid Sequencing Kit Box Barcode
- [x] Plate 2 will not currently be populated

Well-level:
- [x] Movie Acquisition Time (hours) should be limited to the original movie time options
- [x] Include Base Kinetics should be limited to true or false
- [x] Library Concentration (pM) should be a floating point number
- [x] Polymerase Kit should be a string of a certain format

Sample sheet well-level: (scope moved to  #966 )
- [x] Automation parameters is automatically generated
- [x] Adapters / Barcodes is automatically generated
- [x] Barcode name is automatically generated
- [x] Biosample name is automatically generated

**Dependencies**
This story is blocked by the following dependencies:
- #963

**Comment by BenTopping** [comment]
Closing as in the Done column
