### ISSUE TITLE
DPL-740 - As developers we need to modify the pacbio run so that it can have more than one plate as Revio requires multi-plate support

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#976]
**User story**
As developers we need to modify the pacbio run so that it can have more than one plate as Revio requires multi-plate support

**Who are the primary contacts for this story**
Steve / Ben

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] A run should be able to have more than one plate
- [x] If the instrument is not Revio then a run can only have 1 plate
- [x] if the instrument is Revio then a run can have 2 plates
- [ ] a process diagram to create a shared understanding of how it works

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Task list - first pass where we are still limiting to create single plate:

**Create:**
- [ ] Factory should create a run from run_attributes
- [ ] Factory should not be valid if run is not valid e.g. sequencing kit box barcode is empty
- [ ] Factory should create wells from well_attributes - well_attributes= method will build a well for each set of attributes and add them to the plate
- [ ] Factory should not be valid if wells are not valid e.g. column is empty
- [ ] Factory should not be valid if wells are not in correct positions e.g. well has ro D and column 12
- [ ] Factory should not be valid if wells are not contiguous e.g. A1 and D1 are filled
- [ ] Factory should create a plate
- [ ] construct_resources! should save the run, plate and wells and fail if the run is invalid
- [ ] if the run is invalid there should be valid, sensible error messages

**Update:**
- [ ] If the run attributes has an id then the run should be updated
- [ ] The run should be found from the id
- [ ] The plate should be found via the run
- [ ] The wells should be updated via the well_attributes
- [ ] If the well_attributes have an id then the well should be retrieved
- [ ] If the well_attributes do not have an id then the well should be created
- [ ] If an existing well id is not in the well_attributes does not exist then the well should be marked for destruction
- [ ] A run should not be valid if the updated attributes are not valid
- [ ] A run should not be valid if the updated well_attributes are not valid
- [ ] The wells should be checked with the well position validator expect for those that are marked for destruction
- [ ] construct_resources! should save the run, plate and wells and fail if the run is invalid
- [ ] if the run is invalid there should be valid, sensible error messages

**Run resource:**
- [ ] construct_resources! should be run on create and update
- [ ] remove well_attributes

**Run model:**
- [ ] delegate attributes and construct_resources! to run factory
- [ ] run_factory should generate new RunFactory
- [ ] add validates_nested to run model
- [ ] remove accepted_nested_attributes_for and well_attributes

**Plate model:**
- [ ] remove accepted_nested_attributes_for, well_attributes, delete_removed_wells and create_or_update_wells

**Comment by BenTopping** [comment]
[pacbio-run-revio-example-request_updated.txt](https://github.com/sanger/traction-service/files/11736027/pacbio-run-revio-example-request_updated.txt)

**Comment by harrietc52** [comment]
On Deployment to UAT a few errors appeared with regards to the rake task. 

![Screenshot 2023-06-26 at 17 15 21](https://github.com/sanger/traction-service/assets/11446617/c0a33b47-f448-4262-b798-e37a32d47d0e)
![Screenshot 2023-06-26 at 17 13 02](https://github.com/sanger/traction-service/assets/11446617/19aa4bbf-2028-4ab3-977e-e94781ffd628)
![Screenshot 2023-06-26 at 17 04 55](https://github.com/sanger/traction-service/assets/11446617/d4b96a9f-4de4-4726-b6c6-57d37904d778)
![Screenshot 2023-06-26 at 16 57 00](https://github.com/sanger/traction-service/assets/11446617/a6cd7371-938c-4400-9a16-156211046872)

Rake task might need to be updated. To check all runs have a plate, and all plates have wells.
