### ISSUE TITLE
DPL-741 As a user (James M) I would like to be able to see pacbio pool names in the MLWH

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-service#990]
**User story**
As a user (James M) I would like to be able to see pacbio pools names in the multi-lims warehouse (MLWH)

**Who are the primary contacts for this story**
James M, Paul H

**Who is the nominated tester for UAT**
James M, Paul H

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Add a new column to the pac_bio_run table in the multi lims warehouse to store the pacbio pool names
~~Rename MLWH 'pacbio_library_tube_name' column to be more relevant to its sample name content~~
- [ ] Update the pacbio MLWH message to include the new column with the correct pool name value (TRAC-2-XXXX)
- [ ] Ensure that when a pool is edited the message is rebroadcasted to the MLWH ?
- [ ] Remove plate_barcode from pacbio message and make column optional in MLWH
- [ ] Update RT (details below) when in testing and complete.

**Comment by TWJW-SANGER** [comment]
Adding link to RT that created this: https://rt.sanger.ac.uk/Ticket/Display.html?id=770163
