### ISSUE TITLE
DPL-744 - As developers we need to modify the message that we send to the warehouse to ensure it contains the correct information for a Revio run

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#992]
**User story**
As developers we need to modify the message that we send to the warehouse to ensure it contains the correct information for a Revio run

**Who are the primary contacts for this story**
Steve / Carol

**Who is the nominated tester for UAT**
Carol

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] there should be an identifier for each plate - number
- [x] modify the message to use the run rather than the plate so we can still send a single message
- [x] use the wells for a run to get information for each sample
- [x] add `plate_number` to uniqueness constraint `unique_pac_bio_entry` for `pac_bio_run` MLWH table

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by harrietc52** [comment]
Q: 
Which Traction Service branch should I check out from, for DPL-744?
What is the new info to send? `plate_number` and move skbb from run to plate?
What fields should these end up in in MLWH

**Comment by harrietc52** [comment]
MLWH `pacbio_run` table

**Comment by harrietc52** [comment]
Dependent on https://github.com/sanger/unified_warehouse/pull/522

**Comment by harrietc52** [comment]
On Deployment (including downtime):

1. Alert NPG (Marina) that we are going to re-create all the data in the `pac_bio_run` MLWH table, as they use the id's for other things. Also let Carol Scott know when this will be in production as she will need to make some changes NPG end to support plate numbers.
2. Traction Service deployment, of the new messaging code
3. Do the rebroadcast to back populate MLWH `plate_number` 
`Pacbio::Run.all.each { |run| Messages.publish(run, Pipelines.pacbio.message) }`
4. Run the Unified Warehouse migration to add the new index (https://github.com/sanger/unified_warehouse/pull/522)

**Comment by harrietc52** [comment]
## Deploying to Production

1. Alert NPG (Marina) that we are going to re-create all the data in the `pac_bio_run` MLWH table, as they use the id's for other things. Also let Carol Scott know when this will be in production as she will need to make some changes NPG end to support plate numbers.

2. Traction Service deployment, of the new messaging code
(Latest Traction Service version on Prod: `v6.0.0`)

`ansible-playbook -vv deploy_traction_service.yml -i environments/uat -e "github_branch=v<release>" -e "full_deploy=true reload_nginx=true skip_migrations=true"`

3. Do the rebroadcast to back populate MLWH `plate_number` 
`Pacbio::Run.all.each { |run| Messages.publish(run, Pipelines.pacbio.message) }`

(See UAT notes for errors)

4. Run the Unified Warehouse migration to add the new index 
(Latest Traction Service version on Prod: `v1.15.0`)

Deploy latest release, and run the migration to the unified warehouse to update the uniqueness constrain. 

`ansible-playbook -vD deploy_unified_warehouse.yml -i environments/uat -e "github_branch=<release>" -e "full_deploy=true skip_migrations=false"`
