### ISSUE TITLE
DPL-754 Traction to receive QC data endpoint from queue

### ISSUE THREAD

**Issue by emrojo** [sanger/traction-service#996]
**User story**
As TOL I want traction to have a new endpoint to receive QC data.

Qc columns

Sheared Femto Fragment Size (bp)
Post SPRI Concentration (ng/ul)
Post SPRI Volume (ul)
Final NanoDrop 260/280
Final NanoDrop 260/230
Final NanoDrop ng/ul
Shearing & QC comments (if applicable)
Date submitted
Priority level (if High or Medium)
Date data required by
Reason for priority

**Who are the primary contacts for this story**
Eduardo Martin

**Who is the nominated tester for UAT**
Charlie (TOL)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] HTTP endpoint that will receive this data 
- [ ] Data will be stored in Traction database as it happens currently

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by TWJW-SANGER** [comment]
This story specifies receiving and recording data from the queue into Traction, but we are not clear on how the data fields below will be used or viewed.

Is data required for the lab to adjust the sample processes? 
When will the data be viewed or queried?
Who will be viewing or querying this data?

@SujitDey2022 is this something you could help us refine?

Fields for the above questions:

Sheared Femto Fragment Size (bp)
Post SPRI Concentration (ng/ul)
Post SPRI Volume (ul)
Final NanoDrop 260/280
Final NanoDrop 260/230
Final NanoDrop ng/ul
Shearing & QC comments (if applicable)

**Comment by TWJW-SANGER** [comment]
I have caught up with James from the Long Read team.

Getting these field into the MLWH is the best option in the short term.  He doesn't (yet) need to see these from within Traction, but Tableua report connecting to this data from MLWH will be a good first step.

**Comment by harrietc52** [comment]
Questions:
- @Sangeetha-Bheeman  were you working on something similar?
- Currently QcResults in Traction require the fields `labware_barcode` and `sample_external_id`, might these be provided too?

**Comment by Sangeetha-Bheeman** [comment]
@harrietc52  yes, this is part of what am working now in consumer and I will be working on this soon on traction-service.

**Comment by harrietc52** [comment]
**Traction Service tasks**

- [ ] update schema to add new columns for qc_results table (Date submitted, Priority level (if High or Medium), Date data required by, Reason for priority). These are optional/ only required for TOL?
- [ ] new route in resource, for endpoint to create multiple qc results
- [ ] new controller for route
- [ ] new resource for route
- [ ] new factory, possibly being passed all the qc results to create. this loops through, creating the qc result, and if successful, building the message
- [ ] in factory, get the relevant assay types, using the tol `used_by` to filter them
- [ ] in factory, validation required assay types are present
- [ ] in the resource, if creation of qc results successful, access messages from the factory
- [ ] add config to build MLWH message to pipelines.yml. this wants to be similar to the existing qc_result message (but without qc_decision etc). But it also wants to add new qc result fields such as (Date submitted, Priority level (if High or Medium), Date data required by, Reason for priority)
- [ ] publish message using factory messages and config
- [ ] edit rake task to add new assay types (confirm keys with tol, and check required units)
- [ ] add new `used_by` to assay type model for `tol`

**MLWH / Unified WH tasks**
- [ ] update MLWH table, via migration in unified warehouse, to add new qc_result fields (date submitted etc) possibly? See design of traction MLWH table [here](https://lucid.app/lucidchart/62e931d9-5afc-40db-a885-533196afb88a/edit?viewport_loc=667%2C1876%2C2542%2C1044%2C0_0&invitationId=inv_623f65cd-4e79-41d8-bd80-e367445d3ab8) 
- [ ] check MLWH table inserts new qc assay type fields and values correctly

**Comment by Sangeetha-Bheeman** [comment]
- [ ] Validation
- [ ] Tests for app/models/qc_receptions_factory.rb
- [ ] Tests for the v1/qc_receptions requests  - controller and resource
- [ ] Testing the message.publish
- [ ] Test the assay type for ToL
- [ ]

**Comment by Sangeetha-Bheeman** [comment]
From Steve - Update from meeting 27/07: date_required_by and reason_for_priority are no longer required and can be removed. priority_level is not a qc_result attribute but should be moved to sample.
