### ISSUE TITLE
DPL-755 Sample data from queue to be stored in warehouse (S=S;C=S)

### ISSUE THREAD

**Issue by emrojo** [sanger/traction-service#997]
**User story**
As TOL I want all sample information provided in the message queue to be sent to the warehouse:

- supplier_name
- accession_number
- donor_id

**Who are the primary contacts for this story**
Eduardo Martin

**Who is the nominated tester for UAT**
Charlie (UAT)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Specified fields will be stored in the warehouse

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
@emrojo is this story still relevant? accession_number is already stored in the warehouse and not sure why we need to store supplier_name and donor_id as these fields are not relevant?

**Comment by SujitDey2022** [comment]
@stevieing @emrojo archiving this user-story
